Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import tabulate

data = [['P (atm)', 'V (L/mol)',   'Z']]

for p in [56, 111.3, 222.6, 445.2, 1113, 2226]:
    sol = root(vdw_zero, 0.5, args=(p,))
    
    V = sol.x[0]
    Z = p * V / R / T
    data += [[p, V, Z]]
    
print(tabulate.tabulate(data, headers='firstrow'))


------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 6[0m
[1;32m      3[0m data [38;5;241m=[39m [[[38;5;124m'[39m[38;5;124mP (atm)[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mV (L/mol)[39m[38;5;124m'[39m,   [38;5;124m'[39m[38;5;124mZ[39m[38;5;124m'[39m]]
[1;32m      5[0m [38;5;28;01mfor[39;00m p [38;5;129;01min[39;00m [[38;5;241m56[39m, [38;5;241m111.3[39m, [38;5;241m222.6[39m, [38;5;241m445.2[39m, [38;5;241m1113[39m, [38;5;241m2226[39m]:
[0;32m----> 6[0m     sol [38;5;241m=[39m [43mroot[49m(vdw_zero, [38;5;241m0.5[39m, args[38;5;241m=[39m(p,))
[1;32m      8[0m     V [38;5;241m=[39m sol[38;5;241m.[39mx[[38;5;241m0[39m]
[1;32m      9[0m     Z [38;5;241m=[39m p [38;5;241m*[39m V [38;5;241m/[39m R [38;5;241m/[39m T

[0;31mNameError[0m: name 'root' is not defined

